/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransakcjeRouteImport } from './routes/transakcje'
import { Route as SymulatorRouteImport } from './routes/symulator'
import { Route as RaportyRouteImport } from './routes/raporty'
import { Route as CeleRouteImport } from './routes/cele'
import { Route as BudzetRouteImport } from './routes/budzet'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const TransakcjeRoute = TransakcjeRouteImport.update({
  id: '/transakcje',
  path: '/transakcje',
  getParentRoute: () => rootRouteImport,
} as any)
const SymulatorRoute = SymulatorRouteImport.update({
  id: '/symulator',
  path: '/symulator',
  getParentRoute: () => rootRouteImport,
} as any)
const RaportyRoute = RaportyRouteImport.update({
  id: '/raporty',
  path: '/raporty',
  getParentRoute: () => rootRouteImport,
} as any)
const CeleRoute = CeleRouteImport.update({
  id: '/cele',
  path: '/cele',
  getParentRoute: () => rootRouteImport,
} as any)
const BudzetRoute = BudzetRouteImport.update({
  id: '/budzet',
  path: '/budzet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budzet': typeof BudzetRoute
  '/cele': typeof CeleRoute
  '/raporty': typeof RaportyRoute
  '/symulator': typeof SymulatorRoute
  '/transakcje': typeof TransakcjeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budzet': typeof BudzetRoute
  '/cele': typeof CeleRoute
  '/raporty': typeof RaportyRoute
  '/symulator': typeof SymulatorRoute
  '/transakcje': typeof TransakcjeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budzet': typeof BudzetRoute
  '/cele': typeof CeleRoute
  '/raporty': typeof RaportyRoute
  '/symulator': typeof SymulatorRoute
  '/transakcje': typeof TransakcjeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/budzet'
    | '/cele'
    | '/raporty'
    | '/symulator'
    | '/transakcje'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/budzet'
    | '/cele'
    | '/raporty'
    | '/symulator'
    | '/transakcje'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/budzet'
    | '/cele'
    | '/raporty'
    | '/symulator'
    | '/transakcje'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BudzetRoute: typeof BudzetRoute
  CeleRoute: typeof CeleRoute
  RaportyRoute: typeof RaportyRoute
  SymulatorRoute: typeof SymulatorRoute
  TransakcjeRoute: typeof TransakcjeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transakcje': {
      id: '/transakcje'
      path: '/transakcje'
      fullPath: '/transakcje'
      preLoaderRoute: typeof TransakcjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symulator': {
      id: '/symulator'
      path: '/symulator'
      fullPath: '/symulator'
      preLoaderRoute: typeof SymulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raporty': {
      id: '/raporty'
      path: '/raporty'
      fullPath: '/raporty'
      preLoaderRoute: typeof RaportyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cele': {
      id: '/cele'
      path: '/cele'
      fullPath: '/cele'
      preLoaderRoute: typeof CeleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budzet': {
      id: '/budzet'
      path: '/budzet'
      fullPath: '/budzet'
      preLoaderRoute: typeof BudzetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BudzetRoute: BudzetRoute,
  CeleRoute: CeleRoute,
  RaportyRoute: RaportyRoute,
  SymulatorRoute: SymulatorRoute,
  TransakcjeRoute: TransakcjeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
